### ISSUE TITLE
Backup from automation fails

### ISSUE THREAD

**Issue by DavyRoswinkel** [jcwillox/hass-auto-backup#35] opened 2021-06-03 05:25 UTC
Getting the following error, since update to last core.

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Source: custom_components/auto_backup/__init__.py:302
Integration: Auto Backup (documentation)
First occurred: 07:22:16 (1 occurrences)
Last logged: 07:22:16

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/auto_backup/__init__.py", line 302, in new_snapshot
    data[ATTR_NAME] = datetime.now(self._hass.config.time_zone).strftime(
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'

## System Health

version | core-2021.6.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4630
Installed Version | 1.12.4
Stage | running
Available Repositories | 891
Installed Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17 juni 2021 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 19.03.15
disk_total | 116.7 GB
disk_used | 24.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.7.1), File editor (5.3.1), Grafana (6.3.5), Home Assistant Google Drive Backup (0.104.3), InfluxDB (4.1.1), Samba share (9.5.0), Terminal & SSH (9.1.3), FTP (4.1.0), TimescaleDB (1.1.6), DSMR Reader (0.5.0), phpMyAdmin (0.4.1), Visual Studio Code (3.4.1), MariaDB (2.3.0), ESPHome (1.18.0), Node-RED (9.1.3), Mosquitto broker (6.0.1), TooGoodToGo Home Assistant MQTT Bridge (1.6.0), Zigbee2mqtt Edge (edge)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 10
views | 31
mode | storage

</details>

**Comment by jcwillox** [comment] 2021-06-04 00:31
Ahh, great I can confirm that Auto Backup is currently broken in HA 2021.6, I'll try to get a fix out tonight. 

It turns out they changed the type of `self._hass.config.time_zone` from a tzinfo object to a string, which broke it.
https://github.com/home-assistant/core/commit/bf2d40adfed9b9689bcbb61b18306fa1098f74eb#diff-79667bda301cc51e7bdf9df436c097570bd3ea3bf7a78091029a8fef9df27587

**Comment by jcwillox** [comment] 2021-06-04 08:45
This should be fixed in release [0.7.2](https://github.com/jcwillox/hass-auto-backup/releases/tag/0.7.2).

**Closed by jcwillox** 2021-06-04 08:45 UTC
