### ISSUE TITLE
Log Details (WARNING)

### ISSUE THREAD

**Issue by ChillZwix** [jcwillox/hass-auto-backup#87] opened 2023-02-04 22:41 UTC
### The problem

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for auto_backup using this method at custom_components/auto_backup/__init__.py, line 192: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

Home Assistant 2023.2.1

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.01.1

**Comment by jcwillox** [comment] 2023-02-07 10:48
This is a duplicate of #83, and has been fixed in (#85) https://github.com/jcwillox/hass-auto-backup/releases/tag/1.3.1

**Closed** 2023-05-06 14:12 UTC
